"""Mina client backed by miservice, plus an injectable local test double."""

from __future__ import annotations

import asyncio
import json
import threading
import time
from contextlib import asynccontextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any, AsyncContextManager, Awaitable, Callable, Protocol

from miservice import MiAccount, MiNAService, MiTokenStore

from .cookie_login import COOKIE_AUTH_SOURCE


class MinaClientError(RuntimeError):
    """Base class for safe, user-facing Mina errors."""


class MinaAuthError(MinaClientError):
    """Mina rejected authentication or credentials are missing."""


class MinaUpstreamError(MinaClientError):
    """Mina returned an invalid or unsuccessful upstream response."""


class MinaDeviceError(MinaClientError):
    """No usable device was selected."""


@dataclass(frozen=True)
class MinaDevice:
    id: str
    name: str


# Conversation polls run under the client-wide _run lock; without an explicit
# bound a hung upstream (aiohttp default total=300s) stalls every Mina call.
_CONVERSATION_TIMEOUT_SEC = 10.0


class MinaClient(Protocol):
    def login(self) -> str: ...
    def list_devices(self) -> list[MinaDevice]: ...
    def text_to_speech(self, text: str, device_id: str) -> Any: ...
    def play_by_url(self, url: str, device_id: str) -> Any: ...
    def pause(self, device_id: str) -> Any: ...
    def stop(self, device_id: str) -> Any: ...
    def play(self, device_id: str) -> Any: ...
    def set_volume(self, volume: int, device_id: str) -> Any: ...


async def _otp_unavailable(otp_method: str) -> str:
    raise MinaAuthError(
        "小米账号需 OTP 验证：请到管理台「账号与设备」页点击「保存并登录」，"
        "在页面内输入验证码完成登录（无头场景可按 README 在宿主机预登录后拷贝 .mi.token）"
    )


class _CookieTokenAccount(MiAccount):
    """MiAccount that never falls back from a pasted token to password login.

    ``MiAccount.mi_request`` normally clears a token after an auth failure and
    retries through ``login()``, which can trigger the account's OTP flow. A
    token obtained from the Cookies form must remain token-only so an expired
    cookie is reported to that form instead of sending another SMS. ``login``
    only loads the stored token and never contacts the account service.
    """

    async def login(self, sid: str) -> bool:
        # 语音轮询在任何 mi_request 惰性加载 token 之前就调用 login()，
        # 这里必须自行加载，否则粘贴的有效 token 永远不可见。
        if self.token is None and self.token_store is not None:
            self.token = await self.token_store.load_token()
        if self.token and sid in self.token:
            return True
        self._login_error = "Cookies token is unavailable or expired"
        return False

    async def mi_request(self, sid: str, url: str, data: Any, headers: dict[str, Any], relogin: bool = True) -> Any:
        return await super().mi_request(sid, url, data, headers, relogin=False)


def parse_device_list(devices: Any) -> list[MinaDevice]:
    """Map a raw miservice ``device_list`` payload to ``MinaDevice`` entries."""
    result: list[MinaDevice] = []
    for device in devices or []:
        if not isinstance(device, dict):
            continue
        raw_id = device.get("deviceID") or device.get("miotDID")
        if raw_id is None:
            continue
        device_id = str(raw_id)
        name = device.get("alias") or device.get("name") or device_id
        result.append(MinaDevice(id=device_id, name=str(name)))
    return result


class MinaMiserviceClient:
    """Synchronous Mina client bridging to the async miservice library.

    Each call runs a single coroutine via ``asyncio.run``, so this client must
    be used from a synchronous context without a running event loop (FastAPI
    sync endpoints executed in thread-pool workers qualify). If endpoints ever
    become ``async def``, the bridging strategy must change.
    """

    def __init__(
        self,
        username: str | None,
        password: str | None,
        config_dir: str | Path,
        service_factory: Callable[[], AsyncContextManager[MiNAService]] | None = None,
    ) -> None:
        self.username = username
        self.password = password
        self.config_dir = Path(config_dir)
        self.token_path = self.config_dir / ".mi.token"
        self._service_factory = service_factory or self._default_service
        self._lock = threading.RLock()

    def _cookie_token_file(self) -> bool:
        """Return whether the persisted token was generated by Cookies login."""
        try:
            token = json.loads(self.token_path.read_text(encoding="utf-8"))
        except (OSError, ValueError, TypeError):
            return False
        return isinstance(token, dict) and token.get("_auth_source") == COOKIE_AUTH_SOURCE

    @staticmethod
    def _cookie_token(token: dict[str, Any] | None) -> bool:
        return isinstance(token, dict) and token.get("_auth_source") == COOKIE_AUTH_SOURCE

    @asynccontextmanager
    async def _default_service(self):
        try:
            from aiohttp import ClientSession
        except ImportError:
            from miservice.biohttp import ClientSession
        async with ClientSession() as session:
            account_type = _CookieTokenAccount if self._cookie_token_file() else MiAccount
            account = account_type(
                session,
                self.username,
                self.password,
                token_store=MiTokenStore(str(self.token_path)),
                otp_callback=_otp_unavailable,
            )
            yield MiNAService(account)

    def _run(self, op: Callable[[MiNAService], Awaitable[Any]]) -> Any:
        if not (self.username and self.password) and not self.token_path.is_file():
            raise MinaAuthError(
                "Mina 凭据未配置且缺少 token 文件："
                "请配置 xiaomi_user/xiaomi_password，"
                f"或按 README 在宿主机预登录后将 .mi.token 放入 {self.config_dir}"
            )

        async def runner() -> Any:
            async with self._service_factory() as service:
                return await op(service)

        try:
            with self._lock:
                return asyncio.run(runner())
        except MinaClientError:
            raise
        except Exception as exc:
            raise MinaUpstreamError(f"Mina request failed: {exc}") from exc

    def login(self) -> str:
        if not self.username or not self.password:
            raise MinaAuthError("Mina username and password are required")
        self.list_devices()
        return "authenticated"

    def update_credentials(self, username: str | None, password: str | None) -> None:
        if username != self.username or password != self.password:
            self.token_path.unlink(missing_ok=True)
        self.username = username
        self.password = password

    def list_devices(self) -> list[MinaDevice]:
        return parse_device_list(self._run(lambda service: service.device_list()))

    def text_to_speech(self, text: str, device_id: str) -> Any:
        return self._run(lambda service: service.text_to_speech(device_id, text))

    def play_by_url(self, url: str, device_id: str) -> Any:
        return self._run(lambda service: service.play_by_url(device_id, url))

    def pause(self, device_id: str) -> Any:
        return self._run(lambda service: service.player_pause(device_id))

    def stop(self, device_id: str) -> Any:
        return self._run(lambda service: service.player_stop(device_id))

    def play(self, device_id: str) -> Any:
        return self._run(lambda service: service.player_play(device_id))

    def set_volume(self, volume: int, device_id: str) -> Any:
        return self._run(lambda service: service.player_set_volume(device_id, volume))

    async def _invalidate_and_login(self, account: MiAccount) -> bool:
        """Drop a stale micoapi service token and refresh it once."""
        token = account.token or {}
        if self._cookie_token(token) or self._cookie_token_file():
            return False
        token.pop("micoapi", None)
        account.token = token
        if account.token_store:
            await account.token_store.save_token(token)
        return bool(await account.login("micoapi"))

    async def _conversation_events(self, service: MiNAService, device_id: str, hardware: str, after_timestamp: int) -> list[dict[str, Any]]:
        account = service.account
        # Unlike MiAccount.mi_request(), this endpoint uses the session
        # directly, so it must load the persisted token before deciding that
        # an account login is required.  Otherwise every fresh polling
        # request can send another password/OTP login despite .mi.token.
        if account.token is None and account.token_store is not None:
            account.token = await account.token_store.load_token()
        # Mirror MiAccount.mi_request(): a persisted token from another sid
        # (userId/passToken without "micoapi") must still go through login to
        # exchange the passToken for a micoapi serviceToken.
        if not account.token or "micoapi" not in account.token:
            await account.login("micoapi")
        token = account.token or {}
        if "micoapi" not in token:
            raise MinaAuthError("Mina micoapi token is unavailable")
        user_id = str(token.get("userId", ""))
        service_token = self._service_token(token)
        if not user_id or not service_token:
            raise MinaAuthError("Mina micoapi credentials are unavailable")
        timestamp = int(time.time() * 1000)
        # limit=2 mirrors upstream clients; more than two commands within one
        # poll window drop the oldest ones.
        url = (
            "https://userprofile.mina.mi.com/device_profile/v2/conversation"
            f"?source=dialogu&hardware={hardware}&timestamp={timestamp}&limit=2"
        )
        cookies = {"userId": user_id, "serviceToken": service_token, "channel": "MI_APP_STORE", "deviceId": device_id}
        headers = {"User-Agent": getattr(account, "now_ua", "")}

        async def fetch_once() -> tuple[int, Any]:
            async with account._session.get(url, cookies=cookies, headers=headers) as response:
                return response.status, await response.json(content_type=None)

        refreshed = False
        while True:
            status, body = await asyncio.wait_for(fetch_once(), timeout=_CONVERSATION_TIMEOUT_SEC)
            code = body.get("code") if isinstance(body, dict) else None
            message = str(body.get("message", "")) if isinstance(body, dict) else ""
            if status == 401 or code in {401, 2} or "auth" in message.lower():
                if refreshed or not await self._invalidate_and_login(account):
                    if self._cookie_token(token) or self._cookie_token_file():
                        raise MinaAuthError("Cookies 已失效，请重新获取并粘贴")
                    raise MinaAuthError("Mina conversation authentication expired")
                refreshed = True
                token = account.token or {}
                service_token = self._service_token(token)
                cookies["userId"] = str(token.get("userId", user_id))
                cookies["serviceToken"] = service_token
                continue
            if status != 200 or code != 0:
                raise MinaUpstreamError(f"Mina conversation request failed: HTTP {status}, code={code}")
            raw_data = body.get("data")
            data = json.loads(raw_data) if isinstance(raw_data, str) else (raw_data or {})
            records = data.get("records", []) if isinstance(data, dict) else []
            return [
                {
                    "timestamp": int(record.get("time") or 0),
                    "query": str(record.get("query") or ""),
                    "request_id": str(record.get("requestId") or "") or None,
                    "source": "conversation",
                }
                for record in records
                if int(record.get("time") or 0) > after_timestamp and record.get("query")
            ]

    async def _ubus_events(self, service: MiNAService, device_id: str, after_timestamp: int) -> list[dict[str, Any]]:
        messages = await service.get_latest_ask(device_id)
        result: list[dict[str, Any]] = []
        for message in messages or []:
            timestamp = int(message.get("timestamp_ms") or 0)
            answers = (message.get("response") or {}).get("answer", [])
            query = next((str(answer.get("question") or "") for answer in answers if answer.get("question")), "")
            if timestamp > after_timestamp and query:
                result.append({"timestamp": timestamp, "query": query, "request_id": message.get("request_id"), "source": "ubus"})
        return result

    def fetch_voice_events(self, device_id: str, hardware: str, after_timestamp: int = 0) -> list[dict[str, Any]]:
        async def operation(service: MiNAService) -> list[dict[str, Any]]:
            try:
                return await self._conversation_events(service, device_id, hardware, after_timestamp)
            except MinaAuthError:
                # ubus needs the same micoapi credentials; surface the auth
                # failure instead of hiding it behind a doomed fallback.
                raise
            except Exception:
                return await self._ubus_events(service, device_id, after_timestamp)

        return self._run(operation)

    @staticmethod
    def _service_token(token: dict[str, Any]) -> str:
        value = token.get("micoapi")
        if isinstance(value, (tuple, list)):
            return str(value[1] if len(value) > 1 else (value[0] if value else ""))
        if isinstance(value, dict):
            return str(value.get("serviceToken") or value.get("service_token") or "")
        return str(value or "")

    def validate_voice_device(self, device_id: str, hardware: str) -> None:
        self._run(lambda service: self._validate_async(service, device_id, hardware))

    async def _validate_async(self, service: MiNAService, device_id: str, hardware: str) -> None:
        devices = await service.device_list()
        for device in devices or []:
            if str(device.get("deviceID") or device.get("miotDID") or "") == device_id:
                actual = str(device.get("hardware") or "")
                if actual == hardware:
                    return
                raise MinaDeviceError(f"hardware mismatch: configured {hardware}, device reports {actual or 'empty'}")
        raise MinaDeviceError(f"Mina device not found: {device_id}")


class MockMinaClient:
    def __init__(self, device_id: str | None = None) -> None:
        self.device_id = device_id or "mock-device"
        self.calls: list[tuple[str, tuple[Any, ...]]] = []

    def login(self) -> str:
        self.calls.append(("login", ()))
        return "mock-token"

    def list_devices(self) -> list[MinaDevice]:
        self.calls.append(("list_devices", ()))
        return [MinaDevice(id=self.device_id, name="Mock Mina")]

    def text_to_speech(self, text: str, device_id: str) -> Any:
        self.calls.append(("text_to_speech", (text, device_id)))
        return {"ok": True}

    def play_by_url(self, url: str, device_id: str) -> Any:
        self.calls.append(("play_by_url", (url, device_id)))
        return {"ok": True}

    def pause(self, device_id: str) -> Any:
        self.calls.append(("pause", (device_id,)))
        return {"ok": True}

    def stop(self, device_id: str) -> Any:
        self.calls.append(("stop", (device_id,)))
        return {"ok": True}

    def play(self, device_id: str) -> Any:
        self.calls.append(("play", (device_id,)))
        return {"ok": True}

    def set_volume(self, volume: int, device_id: str) -> Any:
        self.calls.append(("set_volume", (volume, device_id)))
        return {"ok": True}

    def validate_voice_device(self, device_id: str, hardware: str) -> None:
        if device_id != self.device_id:
            raise MinaDeviceError(f"Mina device not found: {device_id}")
        if not hardware:
            raise MinaDeviceError("voice hardware is required")

    def fetch_voice_events(self, device_id: str, hardware: str, after_timestamp: int = 0) -> list[dict[str, Any]]:
        self.calls.append(("fetch_voice_events", (device_id, hardware, after_timestamp)))
        return []
